#!/usr/bin/env python3
"""Generate docs/ECONOMICS_FINAL.md from the COMPILED consensus rules.

Every emission figure is parsed out of `meepcoin-econ-dump --project`, which iterates the real
get_block_reward() from the linked consensus headers. Nothing here re-derives emission in Python --
the only arithmetic done locally is calendar dates and inflation percentages, from those figures.

Usage: economics_report.py <path-to-meepcoin-econ-dump> <output.md>
"""
import datetime as dt
import re
import subprocess
import sys

BLOCKS_PER_YEAR = 525960          # 365.25 * 24 * 60, at the compiled 60-second target
GENESIS_TS = 1785283200           # MEEPCOIN_GENESIS_TIMESTAMP


def die(msg):
    print("! " + msg)
    sys.exit(1)


def run(tool):
    r = subprocess.run([tool, "--project"], capture_output=True, text=True)
    if r.returncode != 0:
        die(f"{tool} --project exited {r.returncode}:\n{r.stdout}\n{r.stderr}")
    return r.stdout


def grab(text, pattern, cast=str, label=None):
    m = re.search(pattern, text, re.MULTILINE)
    if not m:
        die(f"could not find {label or pattern} in the tool output")
    return cast(m.group(1))


def when(height):
    """Calendar date of a height, at the compiled 60-second target."""
    return dt.datetime.fromtimestamp(GENESIS_TS + height * 60, dt.timezone.utc)


def fmt_date(height):
    return when(height).strftime("%Y-%m-%d")


def main():
    if len(sys.argv) < 3:
        die("usage: economics_report.py <meepcoin-econ-dump> <output.md>")
    tool, out_path = sys.argv[1], sys.argv[2]
    text = run(tool)

    # --- compiled constants -------------------------------------------------------------------
    coin       = grab(text, r"^COIN\s+=\s+(\d+)", int, "COIN")
    decimals   = grab(text, r"^CRYPTONOTE_DISPLAY_DECIMAL_POINT\s+=\s+(\d+)", int, "decimals")
    supply_par = grab(text, r"^MONEY_SUPPLY\s+=\s+(\d+)", int, "MONEY_SUPPLY")
    shift      = grab(text, r"^effective emission shift\s+=\s+(\d+)", int, "shift")
    tail       = grab(text, r"^tail reward per block\s+=\s+(\d+)", int, "tail")
    target     = grab(text, r"^DIFFICULTY_TARGET_V2\s+=\s+(\d+)", int, "block target")
    unlock     = grab(text, r"^CRYPTONOTE_MINED_MONEY_UNLOCK_WINDOW=\s+(\d+)", int, "unlock")
    genesis    = grab(text, r"^genesis reward \(already=0\)\s+=\s+(\d+)", int, "genesis reward")
    block1     = grab(text, r"^block-1 reward \(already=genesis\)\s+=\s+(\d+)", int, "block-1 reward")

    if "compiled economics MATCH the approved values" not in text:
        die("the tool reports the compiled economics do NOT match the approved values")

    # --- projection table ---------------------------------------------------------------------
    rows = []
    in_table = False
    for line in text.splitlines():
        if line.startswith("height "):
            in_table = True
            continue
        if in_table:
            if line.startswith("------"):
                continue
            m = re.match(r"^(\d+)\s+([\d.]+)\s+([\d.]+)\s+([\d.]+)\s*$", line)
            if not m:
                if line.strip() == "":
                    in_table = False
                continue
            rows.append((int(m.group(1)), float(m.group(2)), m.group(3), m.group(4)))
    if len(rows) < 9:
        die(f"expected 9 projection rows, parsed {len(rows)}")

    tail_h    = grab(text, r"^tail-start height\s+=\s+(\d+)", int, "tail-start height")
    tail_sup  = grab(text, r"^emitted supply at tail start\s+=\s+([\d.]+)", str, "supply at tail start")
    cross_h   = grab(text, r"^height crossing 25,000,000 MEEP\s+=\s+(\d+)", int, "25M crossing")
    cross_sup = grab(text, r"^emitted supply at that height\s+=\s+([\d.]+)", str, "supply at 25M")
    annual    = grab(text, r"^annual tail issuance\s+=\s+([\d.]+)", str, "annual tail")

    annual_f = float(annual)
    burned_meep = genesis / coin

    def pct(numer, denom):
        return f"{100.0 * numer / denom:.4f}%"

    # --- write ---------------------------------------------------------------------------------
    L = []
    a = L.append
    a("# MeepCoin — Final Compiled Economics")
    a("")
    a("> **Every figure below was produced by running `meepcoin-econ-dump --project`**, which links")
    a("> the real consensus headers and iterates the real `get_block_reward()`. This document is")
    a("> generated by `node/economics_report.py` from that output; the only arithmetic done outside")
    a("> the compiled code is calendar dates and inflation percentages.")
    a("")
    a("> **MeepCoin is not hard-capped.** Approximately 25 million MEEP of main emission, followed by")
    a(f"> permanent tail emission of {tail / coin:.11f} MEEP per block.")
    a("")
    a("> PRIVATE DEVELOPMENT CHAIN. Dev/test coins with no monetary value. No public network exists.")
    a("")
    a("## Compiled parameters")
    a("")
    a("| Parameter | Compiled value |")
    a("|---|---|")
    a(f"| Display decimals | {decimals} |")
    a(f"| `COIN` | {coin:,} atomic units per MEEP |")
    a(f"| `MONEY_SUPPLY` (main-emission parameter) | {supply_par:,} atomic = {supply_par / coin:,.0f} MEEP |")
    a(f"| Block target | {target} seconds |")
    a(f"| Effective emission shift | {shift} |")
    a(f"| Permanent tail reward | {tail:,} atomic = {tail / coin:.11f} MEEP per block |")
    a(f"| Mined-output unlock (dev) | {unlock} blocks |")
    a("| Premine | 0 |")
    a("| Founder / developer allocation | 0 |")
    a("| Transaction fees | paid to miners |")
    a("")
    a(f"Blocks per year at a {target}-second target: **{BLOCKS_PER_YEAR:,}**. "
      f"Genesis timestamp {GENESIS_TS} = {when(0).strftime('%Y-%m-%d')} UTC; every date below is "
      f"derived from that at a perfectly-on-target block rate, so treat them as estimates.")
    a("")
    a("## Initial rewards")
    a("")
    a("| | atomic | MEEP |")
    a("|---|---|---|")
    a(f"| Initial (genesis) reward | {genesis:,} | {genesis / coin:.11f} |")
    a(f"| Block-1 reward (after the genesis amount) | {block1:,} | {block1 / coin:.11f} |")
    a("")
    a(f"Block 1 is {genesis - block1:,} atomic units lower than genesis because "
      f"`get_block_reward` computes `(MONEY_SUPPLY - already_generated_coins) >> {shift}` and the "
      f"genesis amount is already counted.")
    a("")
    a("## Emission schedule")
    a("")
    a("`emitted supply` is the total emitted by all blocks strictly *before* that height.")
    a("")
    a("| Milestone | Height | Est. date | Reward at that height (MEEP) | Emitted supply (MEEP) |")
    a("|---|---|---|---|---|")
    labels = ["Genesis", "1 day", "30 days", "Year 1", "Year 5", "Year 10",
              "Year 15", "Year 20", "Year 25"]
    for label, (h, yrs, reward, sup) in zip(labels, rows):
        a(f"| {label} | {h:,} | {fmt_date(h)} | {reward} | {sup} |")
    a("")
    a("## Tail emission")
    a("")
    a("| | Value |")
    a("|---|---|")
    a(f"| Tail-start height | {tail_h:,} |")
    a(f"| Tail-start estimated date | {fmt_date(tail_h)} ({tail_h / BLOCKS_PER_YEAR:.2f} years) |")
    a(f"| Emitted supply at tail start | {tail_sup} MEEP |")
    a(f"| Tail reward per block | {tail / coin:.11f} MEEP |")
    a(f"| Annual tail issuance | {annual} MEEP/year |")
    a("")
    a("The tail floor engages once `(MONEY_SUPPLY - already_generated_coins) >> "
      f"{shift}` falls below the tail, i.e. before the main-emission parameter is reached — so the")
    a("switch to tail emission happens *before* 25,000,000 MEEP, and emission then continues past it.")
    a("")
    a("## Crossing 25,000,000 MEEP")
    a("")
    a("| | Value |")
    a("|---|---|")
    a(f"| Height where emitted supply first reaches 25,000,000 MEEP | {cross_h:,} |")
    a(f"| Estimated date | {fmt_date(cross_h)} ({cross_h / BLOCKS_PER_YEAR:.2f} years) |")
    a(f"| Emitted supply at that height | {cross_sup} MEEP |")
    a("")
    a("Emitted supply **exceeds** 25,000,000 MEEP from this height onward. The 25-million figure is a")
    a("main-emission parameter, not a cap.")
    a("")
    a("## Tail inflation over time")
    a("")
    a("Annual tail issuance is constant in absolute terms, so inflation as a percentage of supply")
    a("falls monotonically without ever reaching zero.")
    a("")
    a("| Emitted supply (MEEP) | Annual tail issuance | Annual inflation |")
    a("|---|---|---|")
    for s in (float(tail_sup), 25_000_000.0, 30_000_000.0, 40_000_000.0, 50_000_000.0):
        a(f"| {s:,.2f} | {annual_f:,.2f} | {pct(annual_f, s)} |")
    a("")
    a("## Emitted, burned and circulating supply — kept separate")
    a("")
    a("These three are not interchangeable and are reported separately throughout:")
    a("")
    a("| Term | Definition | Value |")
    a("|---|---|---|")
    a(f"| **Emitted supply** | every coin the protocol has ever created, including the burned genesis reward | see the schedule above |")
    a(f"| **Burned supply** | the genesis coinbase, paid to an output with no known spend key | {burned_meep:.11f} MEEP |")
    a(f"| **Circulating supply** | emitted − burned | emitted − {burned_meep:.11f} MEEP |")
    a("")
    a("The genesis reward is **included in emitted supply** and **excluded from circulating supply**.")
    a("It is sent to `P = Hs(r·A‖0)·G + B` where `B` is the hash-to-point image of a published")
    a("nothing-up-my-sleeve string. Recovering the spend key would require solving the ed25519")
    a("discrete-log problem for `B`, so the output is **cryptographically unspendable under the")
    a("ed25519 discrete-log assumption** — not information-theoretically impossible. See")
    a("`GENESIS_BURN_EVIDENCE.md`.")
    a("")
    a("Worked example at the 25,000,000 crossing:")
    a("")
    a(f"- emitted     {cross_sup} MEEP")
    a(f"- burned      {burned_meep:.11f} MEEP")
    a(f"- circulating {float(cross_sup) - burned_meep:.11f} MEEP")
    a("")
    a("## Emission-curve shape")
    a("")
    a(f"Shift {shift} is **highly front-loaded and strongly favours early miners** — roughly")
    a(f"{100.0 * float(rows[3][3]) / 25_000_000:.1f}% of the 25-million main-emission parameter is emitted in the first year.")
    a("It is **not technically a premine**: nothing is allocated before launch, no founder or")
    a("developer allocation exists, and every coin must be mined.")
    a("")
    a("## Reproduce")
    a("")
    a("```bash")
    a("~/meepcoin-node/build/release/bin/meepcoin-econ-dump --project")
    a("```")
    a("")
    a("The tool asserts the approved values at both compile time (`static_assert`, so a wrong")
    a("constant fails the build) and run time, and exits non-zero on any mismatch.")
    a("")

    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(L))
    print(f"wrote {out_path} ({len(L)} lines) from compiled tool output")


if __name__ == "__main__":
    main()
