#!/usr/bin/env python3
"""Install every MeepCoin tool source and the CMakeLists that builds them.

RECORDS SOMETHING THAT WAS NEVER RECORDED. The extra tool targets -- econ-dump, emission-probe,
hardfork-test, decimal-test -- were appended to src/meepcoin_genesis/CMakeLists.txt by hand as each
was written. patch_genesis_tool.py reinstalls that directory, so re-running it silently reverted the
CMakeLists to the two-target version and `make meepcoin-econ-dump` became "No rule to make target".
The .cpp files survived only because that patch does not delete unknown files.

This script is now the single record: it copies every tool source from the repo into the node tree
and writes the complete CMakeLists. Run it AFTER patch_genesis_tool.py.

Idempotent.
"""
import os, shutil, sys

REPO = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.expanduser("~/meepcoin-node")
DST = os.path.join(ROOT, "src/meepcoin_genesis")

# (source file in node/, target name, libraries beyond the common set)
TOOLS = [
    ("meepcoin_genesis.cpp",        "meepcoin-genesis",        "cryptonote_core cncrypto common epee"),
    ("meepcoin_blockhashing.cpp",   "meepcoin-blockhashing",   "cryptonote_core cncrypto common epee"),
    ("meepcoin_genesis_v16.cpp",    "meepcoin-genesis16",      "cryptonote_core cncrypto common epee ringct"),
    ("meepcoin_econ_dump.cpp",      "meepcoin-econ-dump",      "cryptonote_basic cncrypto common epee"),
    ("meepcoin_emission_probe.cpp", "meepcoin-emission-probe", "cryptonote_basic cncrypto common epee"),
    ("meepcoin_hardfork_test.cpp",  "meepcoin-hardfork-test",
     "cryptonote_core cryptonote_basic blockchain_db cncrypto common epee ringct"),
    ("meepcoin_decimal_test.cpp",   "meepcoin-decimal-test",
     "cryptonote_basic cryptonote_format_utils_basic serialization cncrypto common epee"),
    ("meepcoin_fee_fallback_test.cpp", "meepcoin-fee-fallback-test",
     "cryptonote_basic cryptonote_format_utils_basic cncrypto common epee"),
    # patch 0007: the wallet fork-rule activation predicate. Links the wallet library because the
    # test calls the PRODUCTION weight estimator rather than a copy of the formula.
    ("meepcoin_fork_activation_test.cpp", "meepcoin-fork-activation-test",
     "wallet rpc_base cryptonote_core cryptonote_basic blockchain_db mnemonics ringct cncrypto "
     "common epee version ${Boost_CHRONO_LIBRARY} ${Boost_LOCALE_LIBRARY} ${ICU_LIBRARIES} "
     "${CMAKE_THREAD_LIBS_INIT}"),
    ("meepcoin_difficulty_sim.cpp", "meepcoin-difficulty-sim",
     "cryptonote_basic cncrypto common epee"),
    ("meepcoin_bootstrap_sim.cpp", "meepcoin-bootstrap-sim",
     "cryptonote_basic cncrypto common epee"),
    ("meepcoin_bootstrap_sweep.cpp", "meepcoin-bootstrap-sweep",
     "cryptonote_basic cncrypto common epee"),
    ("meepcoin_bootstrap_candidates.cpp", "meepcoin-bootstrap-candidates",
     "cryptonote_basic cncrypto common epee"),
    ("meepcoin_attacker_matrix.cpp", "meepcoin-attacker-matrix",
     "cryptonote_basic cncrypto common epee"),
    ("meepcoin_netsim.cpp", "meepcoin-netsim",
     "cryptonote_basic cncrypto common epee"),
]

BOOST = ("${Boost_PROGRAM_OPTIONS_LIBRARY} ${Boost_SYSTEM_LIBRARY} ${Boost_FILESYSTEM_LIBRARY} "
         "${Boost_THREAD_LIBRARY} ${EXTRA_LIBRARIES}")

if not os.path.isdir(DST):
    print(f"! {DST} does not exist -- run patch_genesis_tool.py first")
    sys.exit(1)

lines = ["# MeepCoin tool targets. Generated by node/patch_meepcoin_tools.py -- edit that, not this,",
         "# or the next run of patch_genesis_tool.py will silently drop your target.", ""]

missing = []
for src, target, libs in TOOLS:
    s = os.path.join(REPO, src)
    if not os.path.exists(s):
        missing.append(src)
        continue
    shutil.copyfile(s, os.path.join(DST, src))
    lines += [
        f"add_executable({target} {src})",
        f"target_link_libraries({target} PRIVATE {libs}",
        f"  {BOOST})",
        f'set_property(TARGET {target} PROPERTY RUNTIME_OUTPUT_DIRECTORY "${{CMAKE_BINARY_DIR}}/bin")',
        "",
    ]

if missing:
    print("! missing tool sources in the repo, refusing to write a partial CMakeLists:")
    for m in missing:
        print("   ", m)
    sys.exit(1)

with open(os.path.join(DST, "CMakeLists.txt"), "w") as f:
    f.write("\n".join(lines))

print(f"+ installed {len(TOOLS)} tool sources and a complete CMakeLists")
for _, t, _ in TOOLS:
    print(f"    {t}")
print("MEEPCOIN_TOOLS_OK")
