// Pure command-line configuration for pool/dev/run.mjs's REAL local-daemon mode.
//
// Parsing is deliberately separate from the executable entry point so every refusal below is
// testable without opening WSL, Docker, a listener or a daemon. The older synthetic and recorded
// launchers keep their existing permissive argument handling; this parser is used only after the
// operator explicitly selects `--mode real-local-daemon`.

import {
  artifactDirectoryUser, checkDaemonConfig, DAEMON_PROFILES, PEER_TEST_FIXED_DIFFICULTY,
} from './local_daemon.mjs';
import { coinbaseAddressShapeProblem } from './real_daemon_mode.mjs';
import {
  REAL_DAEMON_MODE, REAL_REFRESH_LIMITS, REAL_SEQUENCE_DEV_MAX_BLOCKS,
  isSupportedRealContextPlan,
} from '../../web-miner/lib/shared/protocol.js';

export const REAL_POOL_USAGE = 'node pool/dev/run.mjs --mode real-local-daemon '
  + '--artifact-dir /home/<user>/meepcoin-<build>[/out] --image meepcoin-build:<tag> '
  + '--rpc-port <1024..65535> --p2p-port <1024..65535> '
  + '[--host 127.0.0.1] [--port 8171] [--wsl-distro Ubuntu] [--uid 1000] [--gid 1000] '
  + '[--expected-image-id sha256:<64 hex>] [--coinbase-address <public testnet address>] '
  + '[--two-slot-assignments true (requires --expected-image-id)] '
  + '[--peer-rpc-port <port> --peer-p2p-port <port> --expected-image-id sha256:<64 hex> '
  + '[--natural-difficulty true --expected-genesis-timestamp <unix seconds> --expected-genesis-hash <64 lowercase hex> '
  + '[--max-genesis-age-seconds <positive integer>]] [--sequence-blocks <2..32>] '
  + '[--refresh-windows <2..4>] [--share-difficulty <1..500>]]';

export class RealPoolCliError extends Error {
  constructor(message) {
    super(message);
    this.name = 'RealPoolCliError';
    this.code = 'bad_real_pool_cli';
  }
}

const FLAGS = new Set([
  'mode', 'artifact-dir', 'image', 'rpc-port', 'p2p-port', 'host', 'port',
  'wsl-distro', 'uid', 'gid', 'expected-image-id', 'coinbase-address',
  'two-slot-assignments',
  'peer-rpc-port', 'peer-p2p-port', 'natural-difficulty', 'expected-genesis-timestamp', 'expected-genesis-hash',
  'max-genesis-age-seconds',
  'sequence-blocks', 'refresh-windows', 'share-difficulty',
]);

function valuesOf(argv) {
  const out = new Map();
  for (let i = 0; i < argv.length; i += 2) {
    const token = argv[i];
    if (typeof token !== 'string' || !token.startsWith('--')) {
      throw new RealPoolCliError(`unexpected argument ${JSON.stringify(token)}`);
    }
    const name = token.slice(2);
    if (!FLAGS.has(name)) throw new RealPoolCliError(`unknown option --${name}`);
    if (out.has(name)) throw new RealPoolCliError(`option --${name} was supplied more than once`);
    const value = argv[i + 1];
    if (typeof value !== 'string' || value.length === 0 || value.startsWith('--')) {
      throw new RealPoolCliError(`option --${name} requires one value`);
    }
    out.set(name, value);
  }
  return out;
}

function required(values, name) {
  const value = values.get(name);
  if (value === undefined) throw new RealPoolCliError(`missing required option --${name}`);
  return value;
}

function integer(values, name, fallback, { min, max }) {
  const text = values.get(name);
  if (text === undefined) return fallback;
  if (!/^(?:0|[1-9][0-9]*)$/.test(text)) {
    throw new RealPoolCliError(`--${name} must be a canonical decimal integer`);
  }
  const value = Number(text);
  if (!Number.isSafeInteger(value) || value < min || value > max) {
    throw new RealPoolCliError(`--${name} must be in [${min}, ${max}]`);
  }
  return value;
}

/**
 * Parse the explicit real-daemon CLI. No side effect occurs here.
 *
 * `runId` is generated by the entry point and injected by tests. It is used only to name the one
 * fresh WSL data directory that the owned daemon creates. Post-run chain data is retained rather
 * than recursively deleted; run.mjs prints the exact path and states that policy before Start.
 */
export function parseRealPoolCli(argv, { runId } = {}) {
  if (!Array.isArray(argv)) throw new RealPoolCliError('argv must be an array');
  if (typeof runId !== 'string' || !/^[0-9a-f]{16}$/.test(runId)) {
    throw new RealPoolCliError('runId must be exactly 16 lowercase hexadecimal characters');
  }
  const values = valuesOf(argv);
  if (required(values, 'mode') !== REAL_DAEMON_MODE) {
    throw new RealPoolCliError(`--mode must be ${REAL_DAEMON_MODE}`);
  }

  const artifactDir = required(values, 'artifact-dir');
  const user = artifactDirectoryUser(artifactDir);
  if (!user) {
    throw new RealPoolCliError('--artifact-dir must be a /home/<user>/meepcoin-<build> path, optionally ending in /out');
  }
  const host = values.get('host') ?? '127.0.0.1';
  const port = integer(values, 'port', 8171, { min: 1024, max: 65535 });
  const rpcPort = integer(values, 'rpc-port', null, { min: 1024, max: 65535 });
  const p2pPort = integer(values, 'p2p-port', null, { min: 1024, max: 65535 });
  if (rpcPort === null) throw new RealPoolCliError('missing required option --rpc-port');
  if (p2pPort === null) throw new RealPoolCliError('missing required option --p2p-port');
  if (new Set([port, rpcPort, p2pPort]).size !== 3) {
    throw new RealPoolCliError('--port, --rpc-port and --p2p-port must be three different ports');
  }
  const uid = integer(values, 'uid', 1000, { min: 1, max: 60000 });
  const gid = integer(values, 'gid', 1000, { min: 1, max: 60000 });
  const walletAddress = values.get('coinbase-address') ?? null;
  if (values.has('two-slot-assignments') && values.get('two-slot-assignments') !== 'true') {
    throw new RealPoolCliError('--two-slot-assignments must be exactly true when supplied');
  }
  const twoSlotAssignments = values.has('two-slot-assignments');
  const paired = values.has('peer-rpc-port') || values.has('peer-p2p-port');
  if (values.has('natural-difficulty') && values.get('natural-difficulty') !== 'true') {
    throw new RealPoolCliError('--natural-difficulty must be exactly true when supplied');
  }
  const naturalDifficulty = values.has('natural-difficulty');
  if (naturalDifficulty && !paired) {
    throw new RealPoolCliError('--natural-difficulty requires a private daemon pair');
  }
  if (naturalDifficulty && !values.has('expected-genesis-timestamp')) {
    throw new RealPoolCliError('--natural-difficulty requires --expected-genesis-timestamp');
  }
  if (naturalDifficulty && !values.has('expected-genesis-hash')) {
    throw new RealPoolCliError('--natural-difficulty requires --expected-genesis-hash');
  }
  if (!naturalDifficulty && values.has('expected-genesis-timestamp')) {
    throw new RealPoolCliError('--expected-genesis-timestamp requires --natural-difficulty');
  }
  if (!naturalDifficulty && values.has('expected-genesis-hash')) {
    throw new RealPoolCliError('--expected-genesis-hash requires --natural-difficulty');
  }
  if (!naturalDifficulty && values.has('max-genesis-age-seconds')) {
    throw new RealPoolCliError('--max-genesis-age-seconds requires --natural-difficulty');
  }
  const expectedGenesisTimestamp = naturalDifficulty
    ? integer(values, 'expected-genesis-timestamp', null, { min: 1, max: Number.MAX_SAFE_INTEGER })
    : null;
  const expectedGenesisHash = naturalDifficulty ? values.get('expected-genesis-hash') : null;
  if (naturalDifficulty && !/^[0-9a-f]{64}$/.test(expectedGenesisHash)) {
    throw new RealPoolCliError('--expected-genesis-hash must be exactly 64 lowercase hexadecimal characters');
  }
  const maxGenesisAgeSeconds = integer(values, 'max-genesis-age-seconds', null,
    { min: 1, max: Number.MAX_SAFE_INTEGER });
  if (paired && (!values.has('peer-rpc-port') || !values.has('peer-p2p-port'))) {
    throw new RealPoolCliError('paired mode requires both --peer-rpc-port and --peer-p2p-port');
  }
  if (paired && twoSlotAssignments) {
    throw new RealPoolCliError('paired sequence/refresh mode cannot use --two-slot-assignments');
  }
  if (paired && !values.has('expected-image-id')) {
    throw new RealPoolCliError('paired mode requires --expected-image-id');
  }
  if (!paired && (values.has('sequence-blocks') || values.has('refresh-windows')
    || values.has('share-difficulty'))) {
    throw new RealPoolCliError('sequence/refresh/share options require a private daemon pair');
  }
  const sequenceBlocks = integer(values, 'sequence-blocks', 1,
    { min: 2, max: REAL_SEQUENCE_DEV_MAX_BLOCKS });
  const refreshWindows = integer(values, 'refresh-windows', 1,
    { min: 2, max: REAL_REFRESH_LIMITS.maxWindows });
  const shareDifficulty = values.has('share-difficulty')
    ? integer(values, 'share-difficulty', null, { min: 1, max: PEER_TEST_FIXED_DIFFICULTY })
    : null;
  if (naturalDifficulty && (refreshWindows !== 1 || shareDifficulty !== null || sequenceBlocks > 3)) {
    throw new RealPoolCliError('natural-difficulty mode allows at most three heights, one window each, and no fixed share target');
  }
  if (!isSupportedRealContextPlan(sequenceBlocks, refreshWindows)) {
    throw new RealPoolCliError('sequence-blocks * refresh-windows exceeds the 32-context consent limit');
  }
  if (twoSlotAssignments && !values.has('expected-image-id')) {
    throw new RealPoolCliError('--two-slot-assignments requires --expected-image-id');
  }
  if (walletAddress !== null) {
    const problem = coinbaseAddressShapeProblem(walletAddress);
    if (problem !== null) throw new RealPoolCliError(`--coinbase-address: ${problem}`);
  }

  const peerRpcPort = paired ? integer(values, 'peer-rpc-port', null, { min: 1024, max: 65535 }) : null;
  const peerP2pPort = paired ? integer(values, 'peer-p2p-port', null, { min: 1024, max: 65535 }) : null;
  if (paired && new Set([port, rpcPort, p2pPort, peerRpcPort, peerP2pPort]).size !== 5) {
    throw new RealPoolCliError('pool, daemon A and daemon B require five distinct ports');
  }

  let daemon;
  let peerDaemon = null;
  try {
    const common = {
      wslDistro: values.get('wsl-distro') ?? 'Ubuntu',
      image: required(values, 'image'),
      artifactDir,
      uid,
      gid,
      ...(values.has('expected-image-id') ? { expectedImageId: values.get('expected-image-id') } : {}),
    };
    daemon = checkDaemonConfig({
      ...common,
      runDir: `/home/${user}/meepcoin-private-run-${runId}${paired ? 'a' : ''}`,
      rpcPort, p2pPort,
      ...(paired ? {
        profile: naturalDifficulty ? DAEMON_PROFILES.PRIVATE_EXCLUSIVE_PEER_NATURAL
          : DAEMON_PROFILES.PRIVATE_EXCLUSIVE_PEER_TEST,
        exclusivePeerP2pPort: peerP2pPort,
        ...(naturalDifficulty ? {} : { fixedDifficulty: PEER_TEST_FIXED_DIFFICULTY }),
      } : {}),
    });
    if (paired) peerDaemon = checkDaemonConfig({
      ...common,
      runDir: `/home/${user}/meepcoin-private-run-${runId}b`,
      rpcPort: peerRpcPort, p2pPort: peerP2pPort,
      profile: naturalDifficulty ? DAEMON_PROFILES.PRIVATE_EXCLUSIVE_PEER_NATURAL
        : DAEMON_PROFILES.PRIVATE_EXCLUSIVE_PEER_TEST,
      exclusivePeerP2pPort: p2pPort,
      ...(naturalDifficulty ? {} : { fixedDifficulty: PEER_TEST_FIXED_DIFFICULTY }),
    });
  } catch (err) {
    throw new RealPoolCliError(String(err?.message ?? err).slice(0, 300));
  }

  return Object.freeze({
    host,
    port,
    mode: REAL_DAEMON_MODE,
    twoSlotAssignments,
    realDaemon: Object.freeze({
      daemon,
      // The executable real-daemon path always gives each issuance distinct server-owned work.
      // Direct factory callers remain explicit/opt-in for backwards-compatible test fixtures.
      personalizeTemplates: true,
      ...(paired ? { peer: Object.freeze({ daemon: peerDaemon }) } : {}),
      ...(sequenceBlocks > 1 ? { sequenceBlocks } : {}),
      ...(refreshWindows > 1 ? { refreshWindows } : {}),
      ...(shareDifficulty === null ? {} : { shareDifficulty }),
      ...(expectedGenesisTimestamp === null ? {} : { expectedGenesisTimestamp }),
      ...(expectedGenesisHash === null ? {} : { expectedGenesisHash }),
      ...(maxGenesisAgeSeconds === null ? {} : { maxGenesisAgeSeconds }),
      ...(walletAddress === null ? {} : { walletAddress }),
    }),
  });
}
