// The Wasm adapter can hash an ARBITRARY frozen-v2 context, and the algorithm did not change.
//
// THE DISCRIMINATING CLAIM. Before this round meep_v2_setup() hard-coded one synthetic epoch key,
// seed hash, height and 8-byte template, so a browser could only ever hash that fixture. These
// tests hash REAL daemon-produced block contexts from the committed
// meepow/vectors/block_vectors_v16_devnet.json and require the daemon's own recorded PoW hash.
//
// Where the expected values come from matters: they are `daemon_pow_hash` / `expected_meephash_w_v2`
// in a committed vector file generated by the DAEMON, not by the implementation under test. A bug
// in this adapter cannot move them.

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, resolve } from 'node:path';

import { createV2Hasher, createV2HasherForContext, toHeightU64, MAX_TEMPLATE_BYTES }
  from '../../../web-miner/lib/shared/wasm_hasher.js';
import { bytesToHex, hexToBytes } from '../../../web-miner/lib/shared/target.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(__dirname, '../../..');

// pathToFileURL: a bare absolute Windows path is not a valid ESM specifier (it parses as a
// 'c:' protocol). Same idiom as pool/dev/verifier.mjs.
const createModule = (await import(pathToFileURL(resolve(REPO, 'meepow/wasm/meepow.mjs')).href)).default;

const BLOCK_VECTORS = JSON.parse(
  readFileSync(resolve(REPO, 'meepow/vectors/block_vectors_v16_devnet.json'), 'utf8'),
).vectors;

function contextFor(v) {
  return {
    epochKey: hexToBytes(v.epoch_key),
    seedHash: hexToBytes(v.delayed_seed_input),
    height: v.height,
    template: hexToBytes(v.blob_nonce_zeroed),
  };
}

// TWO ROWS THAT GENUINELY CROSS A SEED TRANSITION.
//
// An earlier revision used heights 0 and 2048. Both have seed_height 0 and therefore the SAME epoch
// key, so the pair could not distinguish an adapter that ignored the epoch key from one that used
// it. Height 2113 is the first committed vector whose seed_height is 2048 and whose epoch key
// actually differs. The assertion below refuses to let this test pass if that ever stops being true.
function rowAtHeight(h) {
  const v = BLOCK_VECTORS.find((x) => x.height === h);
  if (!v) throw new Error(`no committed block vector at height ${h}`);
  return v;
}
const ROWS = [rowAtHeight(0), rowAtHeight(2113)];

test('the chosen vectors really do cross a seed/epoch transition', () => {
  const [a, b] = ROWS;
  for (const v of ROWS) {
    assert.match(v.epoch_key, /^[0-9a-f]{64}$/);
    assert.equal(v.epoch_key, v.delayed_seed_input,
      'the daemon feeds one seed hash as BOTH the epoch key and the delayed seed input');
    assert.equal(v.daemon_pow_hash, v.expected_meephash_w_v2);
    assert.equal(v.daemon_agrees_with_independent_meephash, true);
  }
  // THE POINT OF THE PAIR. Without these, the test below would not be discriminating.
  assert.notEqual(a.epoch_key, b.epoch_key, 'both rows share an epoch key; the pair proves nothing');
  assert.notEqual(a.seed_height, b.seed_height, 'both rows share a seed height');
  assert.equal(a.seed_height, 0);
  assert.equal(b.seed_height, 2048);
  assert.notEqual(a.height, b.height);
  assert.notEqual(a.blob_nonce_zeroed, b.blob_nonce_zeroed);
});

test('arbitrary real block contexts reproduce the daemon pow hash', async () => {
  for (const v of ROWS) {
    const h = await createV2HasherForContext(createModule, contextFor(v));
    try {
      assert.equal(h.isActive(), true);
      const got = bytesToHex(h.hashOne(v.nonce));
      assert.equal(got, v.daemon_pow_hash,
        `height ${v.height} nonce ${v.nonce}: adapter disagreed with the daemon`);
      assert.equal(h.hashCalls, 1);
    } finally {
      h.free();
    }
  }
});

test('two different real contexts give different hashes for the same nonce', async () => {
  // The failure this catches: an adapter that ignores its arguments and keeps hashing one fixture
  // would return the SAME bytes here.
  const nonce = 7;
  const hashes = [];
  for (const v of ROWS) {
    const h = await createV2HasherForContext(createModule, contextFor(v));
    hashes.push(bytesToHex(h.hashOne(nonce)));
    h.free();
  }
  assert.notEqual(hashes[0], hashes[1], 'the context is still being ignored');
});

test('the synthetic wrapper still reproduces every committed v2 known-answer vector', async () => {
  const lines = readFileSync(resolve(REPO, 'meepow/vectors/vectors_v2.txt'), 'utf8').trim().split('\n');
  const h = await createV2Hasher(createModule);
  try {
    let checked = 0;
    for (const line of lines) {
      const [tag, nparents, nonce, hex] = line.trim().split(/\s+/);
      if (tag !== 'v2' || nparents !== '4') continue;
      assert.equal(bytesToHex(h.hashOne(Number(nonce))), hex, `synthetic vector nonce ${nonce}`);
      checked++;
    }
    assert.equal(checked, 20, 'expected all 20 committed v2 vectors');
  } finally {
    h.free();
  }
});

test('malformed contexts are refused BEFORE any allocation or hashing', async () => {
  const base = contextFor(ROWS[0]);
  const cases = [
    ['epochKey too short', { ...base, epochKey: new Uint8Array(31) }, /epochKey must be exactly 32/],
    ['epochKey too long', { ...base, epochKey: new Uint8Array(33) }, /epochKey must be exactly 32/],
    ['seedHash wrong type', { ...base, seedHash: 'deadbeef' }, /seedHash must be a Uint8Array/],
    ['empty template', { ...base, template: new Uint8Array(0) }, /template must not be empty/],
    ['template not bytes', { ...base, template: [1, 2, 3] }, /template must be a Uint8Array/],
    ['oversized template', { ...base, template: new Uint8Array(MAX_TEMPLATE_BYTES + 1) }, /at most/],
    ['non-integer height', { ...base, height: 1.5 }, /height must be an integer/],
    ['unsafe Number height', { ...base, height: Number.MAX_SAFE_INTEGER + 2 }, /MAX_SAFE_INTEGER/],
    ['negative height', { ...base, height: -1n }, /unsigned 64-bit/],
    ['height above uint64', { ...base, height: 1n << 64n }, /unsigned 64-bit/],
    ['non-canonical height string', { ...base, height: '007' }, /canonical decimal/],
    ['not an object', null, /context must be an object/],
  ];
  for (const [name, ctx, re] of cases) {
    await assert.rejects(
      () => createV2HasherForContext(createModule, ctx),
      re,
      `${name} should have been refused`,
    );
  }
});

test('height keeps full uint64 range without Number precision loss', () => {
  assert.equal(toHeightU64('18446744073709551615'), (1n << 64n) - 1n);
  assert.equal(toHeightU64(2n ** 60n), 2n ** 60n);
  assert.equal(toHeightU64(0), 0n);
  // The exact hazard: 2^53 + 1 is not representable as a Number, so it must not be accepted as one.
  assert.throws(() => toHeightU64(2 ** 53 + 1), /MAX_SAFE_INTEGER/);
  // As a string it survives intact.
  assert.equal(toHeightU64('9007199254740993'), 9007199254740993n);
});

test('teardown is defined behaviour, and use-after-teardown is an error not a zero hash', async () => {
  const h = await createV2HasherForContext(createModule, contextFor(ROWS[0]));
  assert.equal(h.isActive(), true);
  h.free();
  assert.equal(h.isActive(), false);
  h.free(); // idempotent
  assert.throws(() => h.hashOne(0), /already freed/);
});

test('an invalid context is rejected before any module is created', async () => {
  // WHAT THIS DOES AND DOES NOT SHOW. Each createV2HasherForContext() call here builds its OWN
  // Emscripten module instance, so this is about per-instance setup, NOT about replacing a context
  // inside one live instance. The earlier version of this test claimed the latter; it did not test
  // it. Same-module replacement is covered separately below.
  const good = await createV2HasherForContext(createModule, contextFor(ROWS[0]));
  try {
    assert.equal(bytesToHex(good.hashOne(ROWS[0].nonce)), ROWS[0].daemon_pow_hash);
    await assert.rejects(
      () => createV2HasherForContext(createModule, { ...contextFor(ROWS[1]), template: new Uint8Array(0) }),
      /template must not be empty/,
    );
    // The rejected setup did not disturb this instance.
    assert.equal(good.isActive(), true);
    assert.equal(bytesToHex(good.hashOne(ROWS[0].nonce)), ROWS[0].daemon_pow_hash);
  } finally {
    good.free();
  }
});

test('two independently owned module instances each keep their own context', async () => {
  // Two SEPARATE module instances, which is what the pool and a worker each have. Both are freed.
  const a = await createV2HasherForContext(createModule, contextFor(ROWS[0]));
  const b = await createV2HasherForContext(createModule, contextFor(ROWS[1]));
  try {
    assert.equal(bytesToHex(a.hashOne(ROWS[0].nonce)), ROWS[0].daemon_pow_hash);
    assert.equal(bytesToHex(b.hashOne(ROWS[1].nonce)), ROWS[1].daemon_pow_hash);
    // Interleaved, to catch one instance clobbering the other's context.
    assert.equal(bytesToHex(a.hashOne(ROWS[0].nonce)), ROWS[0].daemon_pow_hash);
    assert.notEqual(bytesToHex(a.hashOne(3)), bytesToHex(b.hashOne(3)));
  } finally {
    a.free();
    b.free();
  }
  assert.equal(a.isActive(), false);
  assert.equal(b.isActive(), false);
});

test('a caller cannot mutate the setup arrays while createModule is pending', async () => {
  // The hasher snapshots its inputs BEFORE the first await, so the bytes it validated are the bytes
  // it sets up. Without that, this mutation would change the context out from under it.
  const ctx = contextFor(ROWS[0]);
  let resolveModule;
  const gate = new Promise((r) => { resolveModule = r; });
  const slowCreate = async () => { await gate; return createModule(); };

  const pending = createV2HasherForContext(slowCreate, ctx);
  // Wreck every caller-held array while setup is suspended.
  ctx.epochKey.fill(0xff);
  ctx.seedHash.fill(0xff);
  ctx.template.fill(0xff);
  resolveModule();
  const h = await pending;
  try {
    assert.equal(bytesToHex(h.hashOne(ROWS[0].nonce)), ROWS[0].daemon_pow_hash,
      'the caller mutated the context after validation');
  } finally {
    h.free();
  }
});

test('a hash result is always exactly 32 bytes', async () => {
  const h = await createV2HasherForContext(createModule, contextFor(ROWS[0]));
  try {
    const out = h.hashOne(1);
    assert.ok(out instanceof Uint8Array);
    assert.equal(out.length, 32);
  } finally {
    h.free();
  }
});
