/*
 * meepow-v2-helper — long-lived MeepHash-W v2 hashing service for the local development pool.
 *
 * WHY THIS EXISTS. The Phase 1B browser slice recomputes every submitted share with a second
 * instance of the same WebAssembly build. Two instances of one artifact agreeing proves the server
 * did not take the browser's word for it, but it proves nothing about the artifact. This process
 * computes the same hash through the PUBLIC frozen-v2 C++ API, compiled natively, so the pool can
 * require both to agree byte-for-byte before accepting anything.
 *
 * WHAT THAT IS AND IS NOT. It is an independent BUILD/RUNTIME cross-check of the SAME frozen C++
 * source: it can catch Emscripten, glue, compiler, optimiser and runtime divergence. It is NOT a
 * separately authored implementation of the algorithm and it does not make MeepHash-W secure.
 *
 * NO ALGORITHM CODE LIVES HERE. This file only calls meepow::v2::Dataset and meepow::v2::Hasher.
 * It does not copy, fork, tune or reimplement any part of the hash.
 *
 * LIFECYCLE. One process, one 32 MiB Dataset and one 8 MiB Hasher, built once at INIT and reused
 * for every nonce. Hasher is NOT thread-safe, so this process is deliberately single-threaded and
 * the parent serialises requests.
 *
 * PROTOCOL. A strict, versioned, ASCII, line-oriented request/response protocol on stdin/stdout.
 * stdout carries protocol lines ONLY; every diagnostic goes to stderr. Anything unexpected is a
 * fatal error rather than a best-effort guess -- a verifier that guesses is worse than no verifier.
 *
 * THE INPUT GRAMMAR IS CANONICAL, in the same sense the parent's output parser is: exactly one
 * ASCII space between fields, no leading or trailing space, no empty field, unsigned decimals with
 * no leading zeros/sign/exponent/hex form, lowercase hex only, and CR permitted only as the single
 * terminal byte of a CRLF. Every message has ONE spelling. This direction used to be lax -- runs of
 * spaces were collapsed, "01" parsed as 1, and a CR anywhere was discarded -- so the helper
 * accepted lines the protocol does not define and the "strict" claim was true on one side only.
 *
 *   helper -> HELLO <proto> <pid> <token> <algo> <paramset> <distro> <bootid> <sourceid>
 *   server -> INIT <id> <epoch_key_hex64> <seed_hash_hex64> <height> <template_hex>
 *   helper -> READY <id> <dataset_bytes> <scratch_bytes>
 *   server -> HASH <id> <nonce>
 *   helper -> RESULT <id> <hash_hex64>
 *   server -> QUIT
 *   helper -> BYE
 *
 * The startup token is generated by the PARENT and echoed here with this process's Linux PID. It
 * is ownership evidence for shutdown ("is the process at this PID still the child I launched?"),
 * NOT authentication against a hostile local user.
 *
 * WHY HELLO CARRIES distro, bootid AND sourceid.
 *
 *   distro    $WSL_DISTRO_NAME, or "-" when not running under WSL. The parent runs on Windows and
 *             must later inspect and signal THIS process; without pinning the distribution it
 *             would be assuming the default can never change between launch and shutdown.
 *   bootid    /proc/sys/kernel/random/boot_id, or "-" if unreadable. It changes when the WSL VM
 *             restarts, which is exactly when this PID stops meaning anything. It lets the parent
 *             distinguish "the process is confirmed gone" from "I could not look".
 *   sourceid  a build-time constant: the SHA-256 of a sorted inventory of the source files this
 *             binary was compiled from (see scripts/helper-source-inventory.txt). The server
 *             recomputes the same inventory from the working tree and refuses a helper whose
 *             sources do not match. This binds the running binary to a source tree; it is NOT an
 *             attestation of the compiler, flags or the ELF itself.
 *
 * No target is ever accepted here. The helper returns a hash; the server owns target comparison.
 */
#include <cerrno>
#include <cinttypes>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <memory>
#include <string>
#include <vector>

#include <unistd.h>

#include "meepow/v2.hpp"

namespace v2 = meepow::v2;

namespace {

// Protocol version. Bump on any grammar change; the parent refuses a version it does not know.
// v2 added the distro/bootid/sourceid fields to HELLO.
constexpr int PROTOCOL_VERSION = 2;

// Injected by scripts/build-native-helper.sh. A binary built without it says so rather than
// pretending to have an identity, and the server refuses it.
#ifndef MEEPOW_HELPER_SOURCE_ID
#define MEEPOW_HELPER_SOURCE_ID "unknown"
#endif

// Bounds on untrusted input. A line longer than this is fatal, not truncated: silently trimming a
// request would risk answering a different question than the one that was asked.
constexpr size_t MAX_LINE_BYTES = 8192;
// A block template is far smaller than the API's 1 MiB cap; this keeps one line within the bound.
constexpr size_t MAX_TEMPLATE_BYTES = 2048;

std::string tohex(const uint8_t* p, size_t n) {
    static const char* d = "0123456789abcdef";
    std::string s(n * 2, '0');
    for (size_t i = 0; i < n; ++i) {
        s[i * 2] = d[p[i] >> 4];
        s[i * 2 + 1] = d[p[i] & 15];
    }
    return s;
}

// Canonical LOWERCASE hex only. Accepting uppercase would mean two spellings of one value.
bool unhex_strict(const std::string& s, std::vector<uint8_t>& out, size_t expect_bytes) {
    if (s.size() % 2 != 0) return false;
    if (expect_bytes != 0 && s.size() != expect_bytes * 2) return false;
    out.clear();
    out.reserve(s.size() / 2);
    for (size_t i = 0; i < s.size(); i += 2) {
        auto nib = [](char c) -> int {
            if (c >= '0' && c <= '9') return c - '0';
            if (c >= 'a' && c <= 'f') return c - 'a' + 10;
            return -1;  // uppercase and everything else is rejected
        };
        int hi = nib(s[i]);
        int lo = nib(s[i + 1]);
        if (hi < 0 || lo < 0) return false;
        out.push_back(static_cast<uint8_t>((hi << 4) | lo));
    }
    return true;
}

// Printable ASCII plus space only. Rejects NUL, control bytes and anything >= 0x80, so there is no
// encoding ambiguity to reason about.
bool is_plain_ascii(const std::string& s) {
    for (unsigned char c : s) {
        if (c < 0x20 || c > 0x7e) return false;
    }
    return true;
}

/**
 * Split a command line into fields under the CANONICAL grammar: exactly one ASCII space between
 * fields, no leading space, no trailing space, no empty field. Returns false for anything else.
 *
 * The protocol has ONE spelling per message. A splitter that skipped runs of spaces made the arity
 * checks below meaningless and answered "QUIT  " as though it were QUIT -- so the parser the parent
 * relies on was strict in one direction only. The two sides now speak the same exact grammar.
 */
bool split_canonical(const std::string& s, std::vector<std::string>& out) {
    out.clear();
    if (s.empty()) return false;
    if (s.front() == ' ' || s.back() == ' ') return false;
    size_t start = 0;
    for (size_t i = 0; i <= s.size(); ++i) {
        if (i == s.size() || s[i] == ' ') {
            if (i == start) return false;  // an empty field: a doubled space
            out.emplace_back(s, start, i - start);
            start = i + 1;
        }
    }
    return !out.empty();
}

/**
 * Canonical unsigned decimal, matching pool/dev/native_helper.mjs's CANONICAL_UINT exactly.
 *
 * Rejects "01", "+1", "-1", "1e0", "0x10", "1.0" and whitespace. Leading zeros mattered: "01" and
 * "1" are two spellings of one request id, and a protocol with two spellings of a value has an
 * ambiguity where its monotonicity check is supposed to be.
 */
bool parse_u64(const std::string& s, uint64_t& out) {
    if (s.empty() || s.size() > 20) return false;
    if (s.size() > 1 && s[0] == '0') return false;  // no leading zeros; "0" itself is canonical
    for (char c : s) if (c < '0' || c > '9') return false;
    errno = 0;
    char* end = nullptr;
    unsigned long long v = std::strtoull(s.c_str(), &end, 10);
    if (errno != 0 || end != s.c_str() + s.size()) return false;
    out = static_cast<uint64_t>(v);
    return true;
}

bool parse_u32(const std::string& s, uint32_t& out) {
    uint64_t v = 0;
    if (!parse_u64(s, v) || v > 0xffffffffull) return false;
    out = static_cast<uint32_t>(v);
    return true;
}

/**
 * A HELLO field value. Never empty and never containing a space, because the parent's grammar is
 * space-separated and an empty or spaced field would silently change the arity. Anything that is
 * not plain printable ASCII, or is too long, becomes "-" -- an explicit "not available", which the
 * parent treats as "cannot pin this", never as a value.
 */
std::string hello_field(const char* raw, size_t max_len) {
    if (raw == nullptr) return "-";
    const std::string s(raw);
    if (s.empty() || s.size() > max_len) return "-";
    if (!is_plain_ascii(s)) return "-";
    if (s.find(' ') != std::string::npos) return "-";
    return s;
}

/** First line of a /proc file, trimmed. "-" if it cannot be read. */
std::string read_proc_line(const char* path, size_t max_len) {
    std::FILE* f = std::fopen(path, "rb");
    if (f == nullptr) return "-";
    std::string s;
    for (;;) {
        int c = std::fgetc(f);
        if (c == EOF || c == '\n') break;
        if (s.size() >= max_len) { s.clear(); break; }
        s.push_back(static_cast<char>(c));
    }
    std::fclose(f);
    return hello_field(s.empty() ? nullptr : s.c_str(), max_len);
}

[[noreturn]] void fatal(const char* what) {
    std::fprintf(stderr, "helper fatal: %s\n", what);
    std::fflush(stderr);
    std::_Exit(3);
}

void emit(const std::string& line) {
    std::fwrite(line.data(), 1, line.size(), stdout);
    std::fputc('\n', stdout);
    if (std::fflush(stdout) != 0) fatal("stdout write failed");
}

/**
 * Read one line, bounded. Returns false at clean EOF. A line at or over the cap is fatal, and so
 * is any non-ASCII byte.
 */
bool read_line(std::string& out) {
    out.clear();
    for (;;) {
        int c = std::fgetc(stdin);
        if (c == EOF) {
            if (!out.empty()) fatal("truncated line at EOF");
            return false;
        }
        if (c == '\n') break;
        if (out.size() + 1 >= MAX_LINE_BYTES) fatal("input line exceeds the bound");
        out.push_back(static_cast<char>(c));
    }
    // CRLF from a Windows-side writer is tolerated, but ONLY as the single terminal byte. A CR
    // anywhere else was previously discarded silently, so "QU\rIT" was read as QUIT -- a second
    // spelling of a command, invented by the parser rather than by the protocol. Any surviving CR
    // is a control byte and is refused by is_plain_ascii below.
    if (!out.empty() && out.back() == '\r') out.pop_back();
    if (!is_plain_ascii(out)) fatal("non-ASCII or control byte in input line");
    return true;
}

}  // namespace

int main(int argc, char** argv) {
    // argv[1] is the parent-generated startup token, echoed once in HELLO so the parent can bind
    // this exact process to the child it launched.
    if (argc != 2) {
        std::fprintf(stderr, "usage: %s <startup-token>\n", argv[0]);
        return 2;
    }
    const std::string token(argv[1]);
    if (token.empty() || token.size() > 128 || !is_plain_ascii(token)) {
        std::fprintf(stderr, "helper fatal: bad startup token\n");
        return 2;
    }
    for (char c : token) {
        const bool ok = (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f');
        if (!ok) { std::fprintf(stderr, "helper fatal: token must be lowercase hex\n"); return 2; }
    }

    std::setvbuf(stdout, nullptr, _IOFBF, 1 << 16);

    // Identity the parent needs in order to inspect and signal THIS process later, plus the source
    // identity it will check against its own working tree. All three are validated into a
    // space-free ASCII field or reported as "-".
    const std::string distro = hello_field(std::getenv("WSL_DISTRO_NAME"), 128);
    const std::string bootid = read_proc_line("/proc/sys/kernel/random/boot_id", 64);
    const std::string sourceid = hello_field(MEEPOW_HELPER_SOURCE_ID, 128);

    char hello[512];
    std::snprintf(hello, sizeof(hello), "HELLO %d %ld %s %d %d %s %s %s",
                  PROTOCOL_VERSION, static_cast<long>(getpid()), token.c_str(),
                  static_cast<int>(v2::ALGO_VERSION), static_cast<int>(v2::PARAM_SET_ID),
                  distro.c_str(), bootid.c_str(), sourceid.c_str());
    emit(hello);

    std::unique_ptr<v2::Dataset> dataset;
    std::unique_ptr<v2::Hasher> hasher;
    // Monotonic: a request id is never reused for the life of this process, so a stale reply can
    // never be mistaken for a current one.
    uint64_t last_id = 0;

    std::string line;
    while (read_line(line)) {
        std::vector<std::string> tok;
        // Noncanonical spacing is a line this helper does not speak. It is fatal rather than
        // normalised: a verifier that guesses what you meant is worse than no verifier.
        if (!split_canonical(line, tok)) fatal("noncanonical command line");

        if (tok[0] == "QUIT") {
            if (tok.size() != 1) fatal("QUIT takes no arguments");
            emit("BYE");
            // Release before exiting so a leak checker sees a clean teardown.
            hasher.reset();
            dataset.reset();
            return 0;
        }

        if (tok[0] == "INIT") {
            if (hasher) fatal("INIT received twice");
            if (tok.size() != 6) fatal("INIT arity");
            uint64_t id = 0;
            // Two different failures, said separately: "01" is not a canonical id at all, which is
            // not the same complaint as an id that went backwards.
            if (!parse_u64(tok[1], id)) fatal("INIT id is not a canonical unsigned decimal");
            if (id <= last_id) fatal("INIT id must be monotonic");
            last_id = id;

            std::vector<uint8_t> epoch_key, seed_hash, tmpl;
            if (!unhex_strict(tok[2], epoch_key, v2::EPOCH_KEY_SIZE)) fatal("bad epoch key");
            if (!unhex_strict(tok[3], seed_hash, v2::SEED_HASH_SIZE)) fatal("bad seed hash");
            uint64_t height = 0;
            if (!parse_u64(tok[4], height)) fatal("bad height");
            if (tok[5].size() / 2 > MAX_TEMPLATE_BYTES) fatal("template too large");
            if (!unhex_strict(tok[5], tmpl, 0) || tmpl.empty()) fatal("bad template");

            v2::Error err = v2::Error::Ok;
            dataset = v2::Dataset::create(epoch_key.data(), &err);
            if (!dataset) {
                std::fprintf(stderr, "dataset: %s\n", v2::error_string(err));
                fatal("dataset creation failed");
            }
            hasher = v2::Hasher::create(*dataset, seed_hash.data(), height,
                                        tmpl.data(), tmpl.size(), &err);
            if (!hasher) {
                std::fprintf(stderr, "hasher: %s\n", v2::error_string(err));
                fatal("hasher creation failed");
            }

            char ready[128];
            std::snprintf(ready, sizeof(ready), "READY %" PRIu64 " %zu %zu",
                          id, dataset->size_bytes(), v2::SCRATCHPAD_BYTES);
            emit(ready);
            continue;
        }

        if (tok[0] == "HASH") {
            if (!hasher) fatal("HASH before INIT");
            if (tok.size() != 3) fatal("HASH arity");
            uint64_t id = 0;
            if (!parse_u64(tok[1], id)) fatal("HASH id is not a canonical unsigned decimal");
            if (id <= last_id) fatal("HASH id must be monotonic");
            last_id = id;
            uint32_t nonce = 0;
            if (!parse_u32(tok[2], nonce)) fatal("bad nonce");

            uint8_t out[v2::HASH_SIZE];
            const v2::Error err = hasher->hash(nonce, out);
            if (err != v2::Error::Ok) {
                std::fprintf(stderr, "hash: %s\n", v2::error_string(err));
                fatal("hash failed");
            }
            char head[64];
            std::snprintf(head, sizeof(head), "RESULT %" PRIu64 " ", id);
            emit(std::string(head) + tohex(out, v2::HASH_SIZE));
            continue;
        }

        fatal("unknown command");
    }

    // stdin closed without QUIT: the parent went away. Exit non-zero so the parent, if it is still
    // there, treats this as an unexpected termination rather than a clean one.
    return 4;
}
